### ISSUE TITLE
Easy way to run assertions against files

### ISSUE THREAD

**Issue by squito** [ztombol/bats-assert#17]
Just discovered this so apologies if I'm doing something wrong ...

The utils here seem great, but rather than always checking against `$output`, I would like to use the same utils to test against a file which is generated.  I'd really like a simple way to use all of the same goodies but against any file I generated.

Here is my simple hack to enable this for `assert_output`: https://github.com/squito/bats-assert/commit/1ae8341a65fdbe5144129839f5c9d8b4a2d9ef0b

if you think this is useful and have suggestions for the api (should it really be a different function, not `assert_output`?), then I could fix it up, add tests etc and submit a PR.

**UPDATE** I've added this in a few more places, its available in my fork here: https://github.com/squito/bats-assert/tree/assert_output_file

though the only "tests" so far are that I use it, and it seems to work.

**Comment by hikerguy1900** [comment]
I would find file support useful too. This is my first day trying to use BATS. As of now I think I can just cat the file and use the existing asserts.

**Comment by mlopes** [comment]
Shouldn't that be done with bats-files instead?

**Comment by squito** [comment]
ah you're probably right.  I didn't know the whole bats ecosystem.  Maybe even covered by https://github.com/ztombol/bats-file/pull/2
